services:
   steamroller:
    container_name: steamroller
    image: ${DOCKER_IMAGE_TAG}
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'        # 最多使用 1 个 CPU 核心
          memory: 2g         # 最大使用 2GB 内存
        reservations:
          cpus: '0.5'        # 预留 0.5 CPU
          memory: 1g         # 预留 1GB 内存
    healthcheck:
      disable: true
    networks:
      - matrix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.steamroller.rule=Host(`steamroller.kcbaotech.com`)" # 替换为你的域名
      - "traefik.http.routers.steamroller.entrypoints=websecure"
      - "traefik.http.routers.steamroller.service=steamroller"
      - "traefik.http.routers.steamroller.tls.certresolver=dnspodresolver"
      - "traefik.http.services.steamroller.loadbalancer.server.port=3000"

networks:
  matrix-network:
    external: true